### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by lukebakken** [bedla/bedla.github.io#1]
If you are wondering why [this issue](https://github.com/rabbitmq/rabbitmq-server/issues/10074) was deleted, Team RabbitMQ would like you to re-report it here:

https://github.com/rabbitmq/rabbitmq-server/security/advisories

Thank you.

**Comment by bedla** [comment]
I see, will do. Thx

**Comment by bedla** [comment]
here it is https://github.com/rabbitmq/rabbitmq-server/security/advisories/GHSA-pj33-75x5-32j4

**Comment by lukebakken** [comment]
Thank you
